plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.0'
}

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '2.0.0'
    ext.splitties_version = '3.0.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
        classpath 'com.android.tools.build:gradle:8.3.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

kotlin {
    sourceSets.main.kotlin.srcDirs += 'src/main/java'
    sourceSets.test.kotlin.srcDirs += 'src/test/java'
}
